# Global Constants
# ---------------------------

rows = [
    [4, 5],
    [2, 3],
    [2,5],
    [2,3],
    [8,10],
    [7,6],
    [5,6],
    [1,11],
    [2,1],
    [4,1],
    [12, 8],
    [12, 13],
    [13, 17],
    [17, 18],
    [16, 15],
    [14, 15],
    [18, 19],
    [16, 17],
    [28, 29],
    [24, 23],
    [25, 26],
    [26, 28],
    [28, 27],
    [29, 30],
    [23, 18],
    [20, 17],
    [30, 17],
    [28, 29],
    [31, 32],
    [31, 33],
    [25, 31],
    [25, 33],
    [36, 16],
    [35, 16],
    [40, 39]
]

statement_dict = {
    0: False,
    1: "Lessor is not proprietor",
    2: "Lessor is tutor of proprietor",
    3: "Rent can’t be paid two years in advance",
    4: "Lessor is parent of proprietor",
    5: "Leasing can’t last for more than five years.",
    6: "Leasing does not last 20 years or more",
    7: "Leased object is industry oriented",
    8: "Leased object is a house",
    9: "Leased object is perishable",
    10: "Leasing should last at least a year",
    11: "There is power to lease legally",
    12: "The object of the lease is a house in urban zone",
    13: "The leasing subsits after death of lessee",
    14: "The leasing does not end after death of lessee",
    15: "Nor the lessor or lessee have died",
    16: "The leasing ends",
    17: "The leasing remains",
    18: "The family of lessee lives",
    19: "The family members of lesee become new lesees",
    20: "Landlord transmits leased object",
    21: "Lessor notifies transmission",
    22: "Leased object is urban house",
    23: "Lessor notifies new offer to lessee in no more that 30 days",
    24: "lessor modifies terms",
    25: "Lack of custom clause over delivery",
    26: "Custom clause over usage",
    27: "Lessor delivers with necessary items for usage",
    28: "Lack of custom clause over maintenance",
    29: "Lessor must maintain object ",
    30: "Custom clause on lease remaining after transmission",
    31: "Lessee does not inform on necessary reparations",
    32: "Lessee is responsible for reparations",
    33: "Lessee repairs the less important deterioring",
    34: "Rent diminishes",
    35: "Lessee loses total or partial usage",
    36: "Lessor answers for damages and compensation",
    37: "Lessee can make useful or urgent improvements on the object",
    38: "Rent is no longer enforceable for the period",
    39: "Judge determines who will be in charge of reparations",
    40: "Lack of custom clause in notifying need of reparations",
    41: "An undetermined duration of leasing gives the lessor power to define duration"
}

statement_dict2 = {
    0: False,
    1: "El arrendador no es propietario",
    2: "El arrendador es tutor del propietario",
    3: "La renta no puede pagarse dos años por adelantado",
    4: "El arrendador es padre del propietario",
    5: "El arrendamiento no puede durar más de cinco años.",
    6: "El arrendamiento no dura 20 años o más",
    7: "El objeto arrendado está orientado a la industria",
    8: "El objeto arrendado es una casa",
    9: "El objeto arrendado es perecedero",
    10: "El arrendamiento debe durar al menos un año",
    11: "Existe poder para arrendar legalmente",
    12: "El objeto del arrendamiento es una casa en zona urbana",
    13: "El arrendamiento subsiste después de la muerte del arrendatario",
    14: "El arrendamiento no termina después de la muerte del arrendatario",
    15: "Ni el arrendador ni el arrendatario han fallecido",
    16: "El arrendamiento termina",
    17: "El arrendamiento permanece",
    18: "La familia del arrendatario vive",
    19: "Los familiares del arrendatario se convierten en nuevos arrendatarios",
    20: "El arrendador transmite el objeto arrendado",
    21: "El arrendador notifica la transmisión",
    22: "El objeto arrendado es una casa urbana",
    23: "El arrendador notifica nueva oferta al arrendatario en no más de 30 días",
    24: "El arrendador modifica términos",
    25: "Falta de cláusula personalizada sobre la entrega",
    26: "Cláusula personalizada sobre el uso",
    27: "El arrendador entrega con los elementos necesarios para su uso",
    28: "Falta de cláusula personalizada sobre mantenimiento",
    29: "El arrendador debe mantener el objeto",
    30: "Cláusula personalizada en mantenimiento del arrendamiento después de la transmisión",
    31: "El arrendatario no informa sobre reparaciones necesarias",
    32: "El arrendatario es responsable de las reparaciones",
    33: "El arrendatario repara el deterioro menos importante",
    34: "La renta disminuye",
    35: "El arrendatario pierde el uso total o parcial",
    36: "El arrendador responde por daños e indemnizaciones",
    37: "El arrendatario puede hacer mejoras útiles o urgentes en el objeto",
    38: "La renta ya no es exigible por el período",
    39: "El juez determina quién estará a cargo de las reparaciones",
    40: "Falta de cláusula personalizada en notificar necesidad de reparaciones",
    41: "Una duración indeterminada del arrendamiento le da al arrendador poder para definir la duración"
}

def get_matches_from_db(query):
    if not query:
        return []
    return [value for key, value in statement_dict.items() if isinstance(value, str) and query.lower() in value.lower()]
